services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees_db
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  app:
    build: .
    container_name: Employees-Invex
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      INVEX_DATASOURCE_URL: jdbc:mysql://mysql:3306/employees_db
      INVEX_DATASOURCE_USER: root
      INVEX_DATASOURCE_PASSWORD: root
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend: