spring:
  application:
    name: EmployeesInvex

  datasource:
    url: ${INVEX_DATASOURCE_URL}
    username: ${INVEX_DATASOURCE_USER}
    password: ${INVEX_DATASOURCE_PASSWORD}
    #url: jdbc:mysql://mysql:3306/employees_db
    #username: root
    #password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      initialization-fail-timeout: 0
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        rewriteBatchedStatements: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,env,beans
  info:
    env:
      enabled: true
info:
  app:
    name: EmployeesInvex
    version: 1.0.0